Product.create!([
  {name: "Peterbald", price: "78.25", image: "image", description: "The International Cat Association", in_stock: nil, supplier_id: nil},
  {name: "Siberian", price: "65.91", image: "image", description: "The International Cat Association", in_stock: nil, supplier_id: nil},
  {name: "Chartreux", price: "81.26", image: "image", description: "Felis Britannica", in_stock: nil, supplier_id: nil},
  {name: "California Spangled", price: "73.79", image: "image", description: "Fancy Southern Africa Cat Council", in_stock: nil, supplier_id: nil},
  {name: "Norwegian Forest Cat", price: "36.65", image: "image", description: "Felis Britannica", in_stock: nil, supplier_id: nil},
  {name: "Egyptian Mau", price: "91.12", image: "image", description: "Emirates Feline Federation", in_stock: nil, supplier_id: nil},
  {name: "Mekong Bobtail", price: "71.38", image: "image", description: "The International Cat Association", in_stock: nil, supplier_id: nil},
  {name: "Tonkinese", price: "64.29", image: "image", description: "Fancy Southern Africa Cat Council", in_stock: nil, supplier_id: nil},
  {name: "Somali", price: "25.18", image: "image", description: "Emirates Feline Federation", in_stock: nil, supplier_id: nil},
  {name: "Burmese", price: "25.06", image: "image", description: "Felis Britannica", in_stock: nil, supplier_id: nil},
  {name: "Chartreux", price: "47.09", image: "image", description: "Fancy Southern Africa Cat Council", in_stock: nil, supplier_id: nil},
  {name: "Goat", price: "50.0", image: "http://img.memecdn.com/goat-memes-2014_o_4108823.jpg", description: "Likes to stand on things.", in_stock: nil, supplier_id: nil},
  {name: "asdf", price: "70.0", image: "asdf", description: "poisdf", in_stock: nil, supplier_id: nil},
  {name: "sdaf", price: "40.0", image: "sadfou", description: "h;lsdfao", in_stock: nil, supplier_id: nil},
  {name: "Not for Sale", price: "90.0", image: "asdflkjh", description: "This item is not for sale", in_stock: nil, supplier_id: nil},
  {name: "asdf", price: "12.0", image: "asdf", description: "asdfss", in_stock: nil, supplier_id: nil},
  {name: "something", price: "0.0", image: "asdfoij", description: "it's a lie, you can't get something for nothing.", in_stock: nil, supplier_id: nil},
  {name: "sadflkj;", price: "34.0", image: "url(bedge_grunge.png)", description: "background", in_stock: nil, supplier_id: nil},
  {name: "asdfopj", price: "69.0", image: "../../images/bedge_grunge.png", description: "asdfwe", in_stock: nil, supplier_id: nil},
  {name: "wefds", price: "49.0", image: "\"../../images/bedge_grunge.png\"", description: "sdfgoiu", in_stock: nil, supplier_id: nil},
  {name: "camel", price: "20.0", image: "https://slack-imgs.com/?c=1&url=https%3A%2F%2Fupload.wikimedia.org%2Fwikipedia%2Fcommons%2F4%2F43%2F07._Camel_Profile%2C_near_Silverton%2C_NSW%2C_07.07.2007.jpg", description: "Pristine camel for sale", in_stock: nil, supplier_id: nil},
  {name: "Hippo", price: "20.0", image: "http://img.burrard-lucas.com/zambia/full/hippo_charge.jpg", description: "Deadly hippo needs love", in_stock: nil, supplier_id: nil},
  {name: "new nae", price: "34.0", image: "aslkdfjh", description: "rawr", in_stock: nil, supplier_id: nil}
])
